### ISSUE TITLE
test_kernel_control.py and perhaps other tests fail

### ISSUE THREAD

**Issue by doronbehar** [jupyter-xeus/xeus#309] opened 2021-12-15 21:07 UTC
I'm trying to package xeus for NixOS, and I'm getting these errors when running the tests:

```
xeus> Running tests...
xeus> /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/bin/ctest --force-new-ctest-process
xeus> Test project /build/source/build
xeus>     Start 1: test_xin_memory_history_manager
xeus>     Start 2: test_unit_kernel
xeus>     Start 3: test_kernel
xeus>     Start 4: test_kernel_control
xeus>     Start 5: test_kernel_shell
xeus> 1/5 Test #1: test_xin_memory_history_manager ...   Passed    0.00 sec
xeus> 2/5 Test #2: test_unit_kernel ..................   Passed    0.00 sec
xeus> 3/5 Test #3: test_kernel .......................***Failed    2.84 sec
xeus> ============================= test session starts ==============================
xeus> platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
xeus> rootdir: /build/source/build/test
xeus> collected 13 items
xeus> test_kernel.py s.ssFsFs..F.F                                             [100%]
xeus> =================================== FAILURES ===================================
xeus> _____________________ XeusKernelTests.test_execute_result ______________________
xeus> self = <test_kernel.XeusKernelTests testMethod=test_execute_result>
xeus>     def test_execute_result(self):
xeus>         if not self.code_execute_result:
xeus>             raise SkipTest
xeus>         for sample in self.code_execute_result:
xeus>             with self.subTest(code=sample['code']):
xeus>                 self.flush_channels()
xeus> >               reply, output_msgs = self.execute_helper(sample['code'])
xeus> /nix/store/khm5b2hvzi7qw5iy7w6jpl328nyqw6br-python3.9-jupyter_kernel_test-0.4.3/lib/python3.9/site-packages/jupyter_kernel_test/__init
__.py:220:
xeus> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
xeus> /nix/store/khm5b2hvzi7qw5iy7w6jpl328nyqw6br-python3.9-jupyter_kernel_test-0.4.3/lib/python3.9/site-packages/jupyter_kernel_test/__init
__.py:77: in execute_helper
xeus>     validate_message(msg, msg['msg_type'], msg_id)
xeus> /nix/store/khm5b2hvzi7qw5iy7w6jpl328nyqw6br-python3.9-jupyter_kernel_test-0.4.3/lib/python3.9/site-packages/jupyter_kernel_test/msgspe
c_v5.py:141: in validate_message
xeus>     content_vdor.validate(msg['content'])
xeus> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
xeus> self = <jsonschema.validators.create.<locals>.Validator object at 0x7ffff4c764c0>
xeus> args = ({'data': {'text/plain': '6*7'}, 'execution_count': 1, 'metadata': None},)
xeus> kwargs = {}, error = <ValidationError: "None is not of type 'object'">
xeus>     def validate(self, *args, **kwargs):
xeus>         for error in self.iter_errors(*args, **kwargs):
xeus> >           raise error
```

And it keeps on and on. I'm using `jupyter_kernel_test` version 0.4.3 , perhaps there was an API change in it that caused the tests to start failing? Or perhaps with `jsonschema` (tried with both version 4.3.0 and version 3.2.0 of it).

**Comment by JohanMabille** [comment] 2021-12-15 22:07
Indeed, there seems to be a problem with `jupyter_kernel_test` 0.4.3; this is confirmed with this [PR](https://github.com/jupyter-xeus/xeus/pull/310). For now we recommend to use `jupyter_kernel_test` 0.3.0 until the issue is solved.

**Comment by DerThorsten** [comment] 2022-01-07 11:31
The issue arises from   https://github.com/nlohmann/json/issues/2046.
An empty json object is serialized as `null` instead of `{}` for some compilers.
We could use `nl::json(nl::json::value_t::object)` instead of `nl::json::object()` everywhere.
And in particular at the places which yield the failing tests.

**Comment by gregmarr** [comment] 2022-01-07 15:11
> An empty json object is serialized as null instead of {} for some compilers.

That's not quite accurate.  2046 is about certain code constructs compiled by GCC resulting in a `json` C++ object that contains `null` rather than an empty JSON object.  The `nlohmann::json::object()` function will always return a `json` C++ object that contains a JSON object, unless it throws due to invalid arguments being provided.

**Comment by DerThorsten** [comment] 2022-01-07 15:14
@gregmarr you are totally right. Sry for the false report.
We have a a few `nlohmann::json()` instead of `nlohmann::json::object()` in the code

**Comment by DerThorsten** [comment] 2022-01-07 15:17
could be that #315  is enough to fix this

**Comment by SylvainCorlay** [comment] 2022-01-17 21:52
Should we close this as fixed?

**Comment by SylvainCorlay** [comment] 2022-02-06 18:19
It appears to be fixed now.

**Closed by SylvainCorlay** 2022-02-06 18:19 UTC
